Rework the sections and subsections of our docs
kinvolk/flatcar-docs pull request #145
Opened 2020-12-29 18:06 UTC by marga-kinvolk

# Rework the sections and subsections of our docs

This is a major change on how the docs were organized.  The existing structure had been raised by a couple of clients as confusing (mostly because how much emphasis was being put on "clusters"), and I was personally having a very hard time navigating it.

So, I've re-distributed the different pages into sections that made more sense to me and that hopefully will also make more sense to clients.  The main sections are now:
 * Installing (includes the "quickstart", and subsections for Cloud Providers, Virtual Machines and Bare Metal)
 * Provisioning Tools (Ignition, Terraform, Cloud Config, etc)
 * Setup and Operations (includes common customizations, managing clusters, managing storage, etc).
 * Container Runtimes
 * Migrating from CoreOS
 * Reference.

In all moved pages, I've included aliases to the previous location, so that any links already pointing to the previous paths should still work.

## Included changes

On top of changing the structure of the site, I also:
1. Removed the tables from the main index page. These tables didn't go well with the new format.  Instead, the index file is now mostly a plain list of links.
2. Fixed links throughout (most of them had been broken with the migration to the new docs).
3. Updated all github repos to point to kinvolk rather than flatcar-linux
4. Added descriptions to the metadata of most pages so that we can use the nice automatically generated indexes provided by Hugo (the Overview pages now include a list of the pages inside with the descriptions provided).
5. Fixed random errors, typos, outdated content when I came across them.

## Why this is so big

I know this is a large refactor, I'm sorry. Splitting it into pieces is hard because files were moved from many different places, and so moving files around requires the new sections to exist; fixing links requires the files to be in their definitive place (otherwise they need to be fixed several times); and in general I went through all files checking links which meant I also did small fixes here and there and the effort to pull them out was really not worth it.

Note: this change currently includes 2 commits that were sent as separate PRs, I intend to rebase it once those PRs are merged.

# How to use / Testing done

I've been running a local version of the website, checking that the rendered structure makes sense as well as testing that links work correctly.

2020-12-30 05:06 UTC, sayanchowdhury requested changes
💯 on this PR.

A couple of comments. I commented on a couple of kinvolk/etcd references but also skipped a few. Since kinvolk/etcd is not regularly updated it would be better to point to upstream docs.

2020-12-30 10:21 UTC, marga-kinvolk commented on docs/setup/systemd/udev-rules.md
> +description: How to run untis when specific udev events trigger.
Done, thanks for catching this.

2020-12-30 10:22 UTC, marga-kinvolk commented on docs/setup/security/generate-self-signed-certificates.md
> + * [etcd Security Model](https://github.com/kinvolk/etcd/blob/master/Documentation/op-guide/security.md)
Sure, makes a lot of sense, thanks!

2020-12-30 10:25 UTC, marga-kinvolk commented on docs/setup/clusters/discovery.md
>  [etcd-reconf-on-flatcar]: https://github.com/coreos/docs/blob/master/etcd/etcd-live-cluster-reconfiguration.md
Agreed. Filed https://github.com/kinvolk/Flatcar/issues/306 to track that.

2020-12-30 10:25 UTC, marga-kinvolk commented on docs/setup/security/adding-certificate-authorities.md
> +[etcd Security Model](https://github.com/kinvolk/etcd/blob/master/Documentation/op-guide/security.md)
Done, thanks.

2020-12-30 10:26 UTC, marga-kinvolk commented on docs/setup/security/hardening-guide.md
> +[etcd-sec-guide]: https://github.com/kinvolk/etcd/blob/v3.2.11/Documentation/op-guide/security.md
Done, thanks.

2020-12-30 10:39 UTC, marga-kinvolk commented
After fixing the links to point to github.com/etcd-io/etcd, I realized that there's actually a docs site for etcd docs (etcd.io/docs). It makes a lot more sense to point there rather than the github sources, so fixed that now.

2021-01-04 05:42 UTC, sayanchowdhury approved these changes
LGTM

2021-01-04 17:05 UTC, marga-kinvolk commented
Vincent/Joaquim: I intend to submit this tomorrow noon-ish. Please let me know if you intend to review and want me to wait some more.  We can always fix things later, but as this is a large rework, I'm ok waiting a bit more to make sure we're in agreement regarding the new structure.

Cheers.

2021-01-04 17:37 UTC, vbatts commented
right on. How are we testing this repo now? do i pull the kinvolk/website and `make run` or ...?

2021-01-04 17:59 UTC, marga-kinvolk commented
You need both the website and this repo. From the website repo, you need to do `make docs`, `make run` and use the `tools/preview_docs.sh` script.  I'm not sure in which order, I think I just ran all those commands repeatedly until it worked :).

The documentation on how to do it is here: https://github.com/kinvolk/website#testing-documentation-locally

2021-01-04 20:58 UTC, vbatts commented
oh this is much nicer
LGTM

2021-01-04 21:27 UTC, joaquimrocha commented
> You need both the website and this repo. From the website repo, you need to do `make docs`, `make run` and use the `tools/preview_docs.sh` script. I'm not sure in which order, I think I just ran all those commands repeatedly until it worked :).
> 
> The documentation on how to do it is here: https://github.com/kinvolk/website#testing-documentation-locally

It's: `make docs`, then the `tools/preview_docs.sh`, then `make run`.

FWIW this is what I expected the OS & Sec to look into last summer (just to clarify that the current structure so far has been a rough proposal). The changes LGTM.

2021-01-04 21:27 UTC, merged